### ISSUE TITLE
What counts as a line when counting lines?

### ISSUE THREAD

**Issue by griffintench** [griffintench/GuppySimulator#1]
Up until now, when counting lines in classes, I've been counting every single line in the file except for blank lines and lines that are purely comments. Today I wanted to see what would happen if I ignored lines that were nothing but a closing brace, and both Pool and FishGroup went from ~185 lines to ~135 (each). (In the case of Pool, this is largely due to the presence of a whole ton of small methods that exist purely to obey the Rule of Demeter.)

What should count as a line when I'm counting lines?

**Comment by chris-thompson** [comment]
Hi Griffin,

I think it's okay to go ahead and ignore lines that are just closing braces.  I suspect there are purists who would disagree with me, but I think we have to be somewhat sensible about these things while aiming for readability, maintainability, etc., without doing gymnastics to adhere to ideals.  I think striving for the ideal is good but knowing when to bend the rules to accommodate reality is also good.
